##spring:
##  ssl:
##    bundle:
##      jks:
##        server:
##          key:
##            alias: "server"
##          keystore:
##            location: "classpath:server.p12"
##            password: "secret"
##            type: "PKCS12"
##      pem:
##        client:
##          truststore:
##            certificate: "classpath:client.crt"
#
            server:
              ssl:
                key-alias: selfsigned
                key-store: classpath:keystore.jks
                key-store-type: JKS
                key-store-provider: SUN
                key-store-password: Test123Test




            #  http.port=8080
              port: 8443
            #  server.ssl.enabled=true